#!/bin/bash

# Extract raw data using jq
raw_data=$(jq -r '
  "\(.name) 
   \(.height*0.1) 
   \(.weight*0.1) 
   \(.types[0].type.name)" 
' data.json)

# Format using awk and sed
echo "$raw_data" | awk '{
  printf "%s %s %s %s", $1, $2, $3, $4
}' | sed -E '
  s/^([a-z])/\U\1/
  s/ ([a-z])/ \U\1/g
' | awk '{
  printf "%s is of type %s, weighs %.0fkg, and is %.1fm tall.\n", $1, $4, $3, $2
}'
